### ISSUE TITLE
CP-2208 Consider standard behavior for modules that go through lifecycle multiple times

### ISSUE THREAD

**Issue by trentgrover-wf** [Workiva/w_module#13]
From @dustinlessard-wf :
Do we have an idea of how the onLoad Future should be treated in the case where a caller requests it after the module has already been loaded? I expect the caller would be provided a future that immediately completes. If so, we may want our examples to show a pattern for achieving that.

From Trent:
My initial instinct would be that this case could be managed by a specific module's implementation pretty easily (keep track of an _isLoaded boolean and short circuit early within onLoad depending on its value), but I'll file a separate issue for that to investigate / consider whether a standard mechanism should be provided instead.

**Comment by evanweible-wf** [comment]
We've decided to only allow one load/unload cycle per module instance (#63)
