### ISSUE TITLE
CP-2206 CP-2086 Consider separating the setup of a module from it loading

### ISSUE THREAD

**Issue by dustinlessard-wf** [Workiva/w_module#53]
#### Issue:

We have no pattern for knowing when a module has actually finished loading.
#### Use case:

I'd like to have this option so that we can track app-startup.  If we can know when an individual module has finished loading, then we can know when a collection of them have (aka our app)

This would also help to understand the time needed for experiences to load.

#### Why is this:

Although our onLoad function returns a future (implying consumers will be informed of async load-related work being completed), when coupled with invoking actions, there is no way to know that any re-rendering has completed as a result of those initial actions being invoked.
#### Proposed solution:
1. Mark the onLoad function as deprecated and introduce the 'onSetup' function as a functionally equivalent replacement.
2. Everyone migrates to the new hotness known as 'onSetup'.
3. We reintroduce `onLoad` and it returns a future that completes once any state changes invoked from onSetup have propagated / re-rendered.

Seeking feedback @trentgrover-wf @evanweible-wf @maxwellpeterson-wf @sebastianmalysa-wf @srinivasdhanwada-wf @jayudey-wf

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_module/53/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by dustinlessard-wf** [comment]
**Alternative solution**:

1. Leave the `onLoad` getter/function as-is.
2. Introduce a new getter/function named 'onLoadComplete' which signals when a module has completed loading, including any state-changes/re-rendering that were the result of the onLoad function.

**Comment by evanweible-wf** [comment]
This seems to have been addressed by our recent discussions on module lifecycle and subsequent changes.. anyone disagree? @Workiva/web-platform-pp @Workiva/rich-app-platform-pp

**Comment by maxwellpeterson-wf** [comment]
I agree
