### ISSUE TITLE
Add @protected annotation to onLoad, onUnload

### ISSUE THREAD

**Issue by maxwellpeterson-wf** [Workiva/w_module#58]
^

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_module/58/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by maxwellpeterson-wf** [comment]
This has already been done.
